services:
  ollama1:
    image: ollama/ollama:latest
    container_name: ollama1
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama   # persist models

  ollama2:
    image: ollama/ollama:latest
    container_name: ollama2
    ports:
      - "11435:11434" # map container 11434 to host 11435
    volumes:
      - ollama_models:/root/.ollama   # persist models

  app:
    build: .
    restart: always
    ports:
      - "80:3000"
      #- "${PORT}:3000"
      - "3000:3000"
      - "443:3443"
      - "3443:3443"
    volumes:
      - ./src/utils/images:/usr/src/app/src/utils/images
    depends_on:
      - ollama1
      - ollama2

volumes:
  ollama_models:


